# Generated by Django 4.2.13 on 2024-10-30 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('identifiant', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('numero_ligne', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='TemperatureReading',
        ),
        migrations.RemoveField(
            model_name='mesure',
            name='cadre',
        ),
        migrations.RemoveField(
            model_name='mesure',
            name='humidite',
        ),
        migrations.AlterField(
            model_name='cadre',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mesure',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ruche',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rucher',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='ligne',
            name='cadre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lignes', to='hello.cadre'),
        ),
        migrations.AddField(
            model_name='capteur',
            name='ligne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capteurs', to='hello.ligne'),
        ),
        migrations.AddField(
            model_name='mesure',
            name='id_capteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='hello.capteur'),
        ),
    ]
