# Generated by Django 4.2.13 on 2024-11-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_capteur_ligne_delete_temperaturereading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rucher',
            name='localisation',
        ),
        migrations.AddField(
            model_name='rucher',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rucher',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
